// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_services_default = defineTool({
  name: "list_services",
  title: "List AmigoXcel services",
  description: "Returns AmigoXcel's four growth pillars: Talent, Technology, Training, and Media.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pillars = [
      {
        pillar: "Talent",
        summary: "Global recruitment and career placement for grads, migrants, and tech professionals."
      },
      {
        pillar: "Technology",
        summary: "Product engineering, web/app development, and technical consulting for startups and growing businesses."
      },
      {
        pillar: "Training",
        summary: "Job-oriented training and upskilling programs for tech and career readiness."
      },
      {
        pillar: "Media",
        summary: "Brand storytelling, video production, and creative media to help businesses stand out."
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(pillars, null, 2) }],
      structuredContent: { pillars }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_company_info_default = defineTool2({
  name: "get_company_info",
  title: "Get AmigoXcel company info",
  description: "Returns AmigoXcel's positioning, contact email, website, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "AmigoXcel",
      positioning: "Growth Partner \u2014 the engine behind talent, technology, training, and media.",
      tagline: "Not Just Services. The Engine Behind Your Growth.",
      website: "https://amigo-xcel-global-careers.lovable.app",
      contactEmail: "careers@amigoxcel.com",
      markets: ["AU", "US", "UK", "CA", "IN", "NP", "SG", "PH"],
      social: {
        instagram: "https://www.instagram.com/amigoxcel/",
        linkedin: "https://www.linkedin.com/company/108184787/"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/submit-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.0";
import { z } from "npm:zod@^3.25.76";
var submit_contact_default = defineTool3({
  name: "submit_contact",
  title: "Submit a contact / strategy call request",
  description: "Send a new contact submission to AmigoXcel (same as the website contact form). Use this to book a strategy call or ask about services.",
  inputSchema: {
    name: z.string().trim().min(1).max(100).describe("Full name of the person reaching out."),
    email: z.string().trim().email().max(200).describe("Reply-to email address."),
    phone: z.string().trim().max(40).optional().describe("Optional phone number with country code."),
    service: z.string().trim().max(100).optional().describe("Which service they're interested in (Talent, Technology, Training, Media, or Other)."),
    message: z.string().trim().min(1).max(2e3).describe("What they want to discuss.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ name, email, phone, service, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const url = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !anonKey) {
      return { content: [{ type: "text", text: "Backend is not configured." }], isError: true };
    }
    const supabase = createClient(url, anonKey, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { error } = await supabase.from("contact_submissions").insert({
      name,
      email,
      phone: phone ?? "",
      service: service ?? "",
      message
    });
    if (error) {
      return { content: [{ type: "text", text: `Could not submit: ${error.message}` }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Thanks ${name} \u2014 your message reached AmigoXcel. The team replies within 24 hours to ${email}.`
        }
      ],
      structuredContent: { ok: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ysynlyafkhtkdureesqq";
var mcp_default = defineMcp({
  name: "amigoxcel-mcp",
  title: "AmigoXcel",
  version: "0.1.0",
  instructions: "Tools for AmigoXcel, a growth partner across talent, technology, training, and media. Sign in to use list_services and get_company_info to describe what AmigoXcel does, and submit_contact to book a strategy call or send an enquiry.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_company_info_default, submit_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
